"""
Pipeline Stage 4: Combine transcript + visual log and use local esper-3.1
to draft a comprehensive report for each video. Output is a markdown file
ready for senior analyst (Claude) to enrich.
"""
import os
import requests

transcript_dir = r"C:\Users\Shivam Patel\.gemini\antigravity\brain\7b03663a-d01b-4302-8959-0a511c484299\transcripts"
visual_logs_dir = r"C:\Users\Shivam Patel\.gemini\antigravity\brain\7b03663a-d01b-4302-8959-0a511c484299\visual_logs"
reports_dir = r"C:\Users\Shivam Patel\.gemini\antigravity\brain\7b03663a-d01b-4302-8959-0a511c484299"

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "esper-3.1"

VIDEO_LABELS = [
    "video_04", "video_05", "video_06", "video_07",
    "video_08", "video_09", "video_10", "video_11",
]

VIDEO_TITLES = {
    "video_04": "Macro Contextual Context on RSI Rotations",
    "video_05": "Datascience vs Math-Driven Trend Following",
    "video_06": "The Vol-Sizing Use Case",
    "video_07": "What's in the Coming Notebooks?",
    "video_08": "Layer 1 - EWMAC",
    "video_09": "Layer 2 - Breakouts",
    "video_10": "Layer 3 - Acceleration",
    "video_11": "Layer 4 - Skew",
}

SYSTEM_PROMPT = """You are a senior quantitative analyst and scientist with 30+ years of experience 
in systematic trading, machine learning, and multi-factor portfolio construction. 

You are given BOTH the audio transcript AND the visual frame descriptions from a quantitative 
trading bootcamp video. Your job is to produce an ABSOLUTELY EXHAUSTIVE, DETAILED, WORD-FOR-WORD 
report that captures:

1. EVERY concept, theory, and strategy rule discussed verbally
2. EVERY chart shown - asset, timeframe, indicators, parameters, visual patterns marked
3. EVERY line of code visible - exact variable names, functions, values, libraries
4. EVERY formula or equation written on screen or whiteboard - exact mathematical notation
5. EVERY book, paper, or academic reference mentioned or shown
6. EVERY backtest result shown - exact numbers: CAGR, Sharpe, Max DD, Win Rate, etc.
7. Cross-references between what was SAID and what was SHOWN at each timestamp

Format your report with clear numbered sections, subsections, timestamps, code blocks, 
and mathematical notation. Length is a VIRTUE. Do NOT skip, summarize or abbreviate ANYTHING.
Every single word and pixel of information is important."""

def call_ollama(prompt):
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "system": SYSTEM_PROMPT,
        "stream": False,
        "options": {
            "num_ctx": 65536,
            "temperature": 0.1,
        }
    }
    r = requests.post(OLLAMA_URL, json=payload, timeout=900)
    r.raise_for_status()
    return r.json()["response"]

print("=" * 60)
print("STAGE 4: Report Drafting with esper-3.1 (local)")
print("=" * 60)

for label in VIDEO_LABELS:
    draft_path = os.path.join(reports_dir, f"{label}_draft_report.md")
    if os.path.exists(draft_path):
        print(f"[SKIP] {label} — draft already exists")
        continue

    # Load transcript
    transcript_path = os.path.join(transcript_dir, label + "_transcript.txt")
    transcript = ""
    if os.path.exists(transcript_path):
        with open(transcript_path, "r", encoding="utf-8") as f:
            transcript = f.read()
    else:
        print(f"[WARN] No transcript for {label}, proceeding with visuals only")

    # Load visual log
    visual_path = os.path.join(visual_logs_dir, label + "_visual_log.txt")
    visual_log = ""
    if os.path.exists(visual_path):
        with open(visual_path, "r", encoding="utf-8") as f:
            visual_log = f.read()
    else:
        print(f"[WARN] No visual log for {label}, proceeding with transcript only")

    if not transcript and not visual_log:
        print(f"[SKIP] {label} — no data available yet")
        continue

    title = VIDEO_TITLES.get(label, label)
    print(f"\n[START] Drafting report: {label} — '{title}'...")

    # Limit to fit context (65k ctx = ~48k chars each)
    if len(transcript) > 40000:
        transcript = transcript[:40000] + "\n...[transcript truncated]"
    if len(visual_log) > 40000:
        visual_log = visual_log[:40000] + "\n...[visual log truncated]"

    prompt = f"""VIDEO: {label} — "{title}" (Quant Bootcamp 2.0)

=== AUDIO TRANSCRIPT (word-for-word, timestamped) ===
{transcript}

=== VISUAL FRAME DESCRIPTIONS (every 3 seconds, timestamped) ===
{visual_log}

Now write the complete, exhaustive, word-by-word report for this video.
Cross-reference the audio and visuals at each timestamp to give a complete picture.
Include all strategy rules, formulas, code, charts, books, and backtest results:"""

    try:
        report = call_ollama(prompt)
        with open(draft_path, "w", encoding="utf-8") as f:
            f.write(f"# DRAFT REPORT: {label} — {title}\n\n")
            f.write(f"*Generated by local esper-3.1 from transcript + visual analysis*\n")
            f.write(f"*To be enriched by senior quant analyst (Claude)*\n\n")
            f.write("---\n\n")
            f.write(report)
        print(f"[DONE]  Draft saved -> {draft_path}")
    except Exception as e:
        print(f"[ERROR] {label}: {e}")

print("\n" + "=" * 60)
print("ALL DRAFTS COMPLETE — Ready for senior analyst review")
print("=" * 60)
