"""
Pipeline Step 2: For each transcript, call local Ollama esper-3.1 to draft
a long-form structured report. I (the main AI) will then review and enrich it.
"""
import os
import json
import requests

transcript_dir = r"C:\Users\Shivam Patel\.gemini\antigravity\brain\7b03663a-d01b-4302-8959-0a511c484299\transcripts"
reports_dir = r"C:\Users\Shivam Patel\.gemini\antigravity\brain\7b03663a-d01b-4302-8959-0a511c484299"

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "esper-3.1"

VIDEO_META = {
    "skool_video_03": "Video 4",
    "skool_video_04": "Video 5",
    "skool_video_05": "Video 6",
    "skool_video_06": "Video 7",
    "skool_video_07": "Video 8",
    "skool_video_08": "Video 9",
    "skool_video_09": "Video 10",
    "skool_video_10": "Video 11",
}

SYSTEM_PROMPT = """You are a senior quantitative analyst with 30+ years of experience in systematic trading, 
machine learning, and portfolio construction. You have just read a complete transcript of a video lecture 
from a Quant trading bootcamp. 

Your job is to write an EXHAUSTIVE, DETAILED, WORD-BY-WORD report of the video. You must:
1. Document EVERY single concept, formula, strategy rule, code snippet, and reference mentioned.
2. Preserve EXACT quotes where possible.
3. Structure the report with clear numbered sections for each topic discussed.
4. Note every chart, visual, or code demo shown (describe it precisely).
5. Highlight every strategy parameter (e.g., "uses 16/64 EWMAC", "threshold = 2 sigma").
6. Document every academic reference (book titles, author names, paper titles).
7. Do NOT summarize or skip anything. Length is a virtue here. Be comprehensive.

Format: Use markdown with headers (##, ###), bullet points, and code blocks where appropriate."""

def call_ollama(transcript_text, video_label):
    prompt = f"""Below is the complete, timestamped transcript of {video_label} from the Quant Bootcamp 2.0 series.

Write a comprehensive, exhaustive, word-by-word analytical report of this video. 
Document every single concept, strategy rule, formula, visual, and reference without missing anything.

TRANSCRIPT:
{transcript_text}

Now write the full detailed report:"""

    payload = {
        "model": MODEL,
        "prompt": prompt,
        "system": SYSTEM_PROMPT,
        "stream": False,
        "options": {
            "num_ctx": 32768,
            "temperature": 0.1,
            "top_p": 0.9,
        }
    }

    print(f"  Calling Ollama ({MODEL})...")
    response = requests.post(OLLAMA_URL, json=payload, timeout=600)
    response.raise_for_status()
    return response.json()["response"]


print("=" * 60)
print("STEP 2: Ollama Report Drafting — Quant Bootcamp Videos")
print("=" * 60)

for name, label in VIDEO_META.items():
    txt_path = os.path.join(transcript_dir, name + "_transcript.txt")
    draft_path = os.path.join(reports_dir, f"{name}_draft_report.md")

    if not os.path.exists(txt_path):
        print(f"[SKIP] {name} — transcript not found yet.")
        continue

    if os.path.exists(draft_path):
        print(f"[SKIP] {name} — draft already exists.")
        continue

    print(f"\n[START] Drafting report for {label} ({name})...")
    with open(txt_path, "r", encoding="utf-8") as f:
        transcript = f.read()

    # Trim to fit context window if needed (esper-3.1 has large ctx)
    if len(transcript) > 60000:
        print(f"  Transcript long ({len(transcript)} chars), using first 60000 chars...")
        transcript = transcript[:60000]

    try:
        report = call_ollama(transcript, label)
        with open(draft_path, "w", encoding="utf-8") as f:
            f.write(f"# DRAFT REPORT: {label} ({name})\n\n")
            f.write("*Generated by local Ollama esper-3.1 — To be enriched by senior analyst*\n\n")
            f.write("---\n\n")
            f.write(report)
        print(f"[DONE] Draft saved: {draft_path}")
    except Exception as e:
        print(f"[ERROR] {name}: {e}")

print("\n" + "=" * 60)
print("ALL DRAFTS COMPLETE. Ready for senior analyst review.")
print("=" * 60)
